-- Your SQL goes here

-- created by running pg_dump on an empty database that had its entire schema generated by sqlx migrate run
CREATE TABLE public._sqlx_migrations (
    version bigint NOT NULL,
    description text NOT NULL,
    installed_on timestamp with time zone DEFAULT now() NOT NULL,
    success boolean NOT NULL,
    checksum bytea NOT NULL,
    execution_time bigint NOT NULL
);


INSERT INTO public._sqlx_migrations VALUES (20180918150231, 'initial', '2023-01-07 13:30:03.372991+00', true, '\x91fdfae6f08dddf419c78de448fbee9836f901c9550bbc5dd17e7aada780ab3f79bb2f96698e2e24ea5138ab49421928', 39329649);
INSERT INTO public._sqlx_migrations VALUES (20181229171817, 'demon view', '2023-01-07 13:30:03.413473+00', true, '\x5e9a358003e05306ef4f4f6e1924eddb4094708b0ecf74d3cdfc6351d9904f831448fea9ae8d26080562a167391585a0', 1495280);
INSERT INTO public._sqlx_migrations VALUES (20190105154218, 'new audit log', '2023-01-07 13:30:03.415693+00', true, '\x6a0c0b37ae471e5fbfe76fdb7ade8c397829eab332d68c671cabf02f479c242e46ef5942f0f7f0ac262ee4e481c232bc', 20661060);
INSERT INTO public._sqlx_migrations VALUES (20190222212203, 'list functions', '2023-01-07 13:30:03.437845+00', true, '\xf24d166cfa20d41e2ef0f939ba778a530c66049b6c9ab797ef0161f404740bedcd7e76cd60c84884264b2dfc50b4d730', 3591817);
INSERT INTO public._sqlx_migrations VALUES (20190311185303, 'remove old columns', '2023-01-07 13:30:03.442796+00', true, '\x6f2c287016b66cba6283735c0292b0f49205c0e0f648d36f55397f2abd87c4f91c43323d50ef8655dab0cfe6c81f0f82', 6565943);
INSERT INTO public._sqlx_migrations VALUES (20190311200729, 'hash as string', '2023-01-07 13:30:03.450785+00', true, '\xef32d848f9bf9e2df281d640c85ebd1dc5682930a6db0ea96b3fbcdca1e39b561114655dfd1c490eb7400b27809fa57e', 10659559);
INSERT INTO public._sqlx_migrations VALUES (20190312131253, 'nationality', '2023-01-07 13:30:03.462832+00', true, '\x637fb8ce16ec644e4eb72a29b5ef70e6d2abcebf2815c560c97eb5d763bd8f219add736e8fee5ae99be60f3bab0c4b56', 29089448);
INSERT INTO public._sqlx_migrations VALUES (20190314134153, 'score view', '2023-01-07 13:30:03.493318+00', true, '\x2fcfc50f7807f396b3076b51144c21abaff5106da862990c865bac5d77ca319048779aab467df45b8ec6b8f54ed2687c', 7008644);
INSERT INTO public._sqlx_migrations VALUES (20190708102450, 'formula update', '2023-01-07 13:30:03.501509+00', true, '\x4b3a9daa2e0f00a37e39b96dabd53de0dce5412a4d12b92c5db7fe35bb9af62d682737b0544bbdaa529a85fe9749f8a7', 4861332);
INSERT INTO public._sqlx_migrations VALUES (20191002080414, 'fix database design', '2023-01-07 13:30:03.507158+00', true, '\x39411c9294c8de6c6bf3852e546f5ce0de63e12d2d076fe95ab1d9fc53bad17a67debe358d539e70951cdd8faf25a7bf', 6581481);
INSERT INTO public._sqlx_migrations VALUES (20191004164504, 'demon ids', '2023-01-07 13:30:03.514443+00', true, '\xf724312d39962bbf84b4ed5e7312d447e6bd154e923170e1ca1d457b3ddf755c1be6a5108ad88fa7197fe05a74f99d30', 19028961);
INSERT INTO public._sqlx_migrations VALUES (20191009080542, 'record notes', '2023-01-07 13:30:03.534225+00', true, '\xe4ca1c0ed92b7c920496cbdeabe1b72678986a62adcd4f42f390835acc10aa7e46739fac64210bf965ddb9067556e3a3', 2167276);
INSERT INTO public._sqlx_migrations VALUES (20200227174850, 'view cleanup', '2023-01-07 13:30:03.537487+00', true, '\x6f591499b49968282ef97639e530b03dd5b7ee0864709999505ed17db7884c57b4ed4c0b5c34fbc703c909e70061db92', 5496054);
INSERT INTO public._sqlx_migrations VALUES (20200227185921, 'record notes', '2023-01-07 13:30:03.544181+00', true, '\xb04bab4cbc5af15be9bc1e8daf8152f8cac7910fe92fe499ca2d46e2756be99e12dc589a791d84a5e157b52aad66508d', 11244907);
INSERT INTO public._sqlx_migrations VALUES (20200302225154, 'cascade note deletion', '2023-01-07 13:30:03.556301+00', true, '\xa40dccd887afb054fab3401c156124342d31a7d211e527ba7efaf31f5f8a3806353dbb6f3e006f430947a3ca9f98b7df', 1777947);
INSERT INTO public._sqlx_migrations VALUES (20200321014223, 'delete old procedures', '2023-01-07 13:30:03.558841+00', true, '\x593c58b008ccc3ba7fa6164181799027a5417194f4222d4a5118648d322407f1cb0161291db69120fab74149cae82493', 952079);
INSERT INTO public._sqlx_migrations VALUES (20200404074854, 'shadow ban', '2023-01-07 13:30:03.560452+00', true, '\x18751c9978f042fc07d00c172822a5980193f3a4a3c0b3526592bfb62bc0f1d21f1f24a83aa729fdf0e43905bb9e0368', 1026777);
INSERT INTO public._sqlx_migrations VALUES (20200515125343, 'new formula', '2023-01-07 13:30:03.562131+00', true, '\x0f34021456382ee988b3d2cee3b6b94220f14d03a54df9ddf69c5e83df0f948f4725a6e6d46cea3fddad2bfec05cd69b', 3191564);
INSERT INTO public._sqlx_migrations VALUES (20200521101927, 'new formulaagain', '2023-01-07 13:30:03.565956+00', true, '\xa968f4ece848d319ee08d33a718985829d3e1ab750bb59b040f26e9a39f4e45cdee1409a925f9dafa96c6e24455561ad', 3008225);
INSERT INTO public._sqlx_migrations VALUES (20200725072253, 'fix smallint', '2023-01-07 13:30:03.569606+00', true, '\x95c6ba9419304bbfc94748101f15df25cc9ad0a9d623a79a529ce0c57b563cad614744d27cfea3b5768abf50055743a4', 929897);
INSERT INTO public._sqlx_migrations VALUES (20200813055728, 'dash rs', '2023-01-07 13:30:03.572172+00', true, '\x284b4fafa4806850443f56db7773baa0ff89695b6a76b03db9096b7ca46a1a8598ccfe87de8409c891767a9e454d3ab3', 17843517);
INSERT INTO public._sqlx_migrations VALUES (20201221091225, 'no ext progress point', '2023-01-07 13:30:03.590722+00', true, '\xb3e8c79d6783c02e9f724cf10846c4010b6af41cb162ba6db9a498b0bb4948169f445932a929df92cd511a165c39607f', 2301149);
INSERT INTO public._sqlx_migrations VALUES (20210224123230, 'new formula once again', '2023-01-07 13:30:03.593682+00', true, '\xd7ca0aaf2eafd8e223302c8111d0e7131be8c92d8de69f1a852ebc43710186564a992c419956f2e6adf9263d424b6aec', 2329321);
INSERT INTO public._sqlx_migrations VALUES (20210327024242, 'timemachine', '2023-01-07 13:30:03.596528+00', true, '\xda49c4757a45e289c050fd4acd40296778e33a3b04543c77fc1e1cd6f147fef41e8c96ab1f61b9e2168b0e8b3a445e15', 963020);
INSERT INTO public._sqlx_migrations VALUES (20210419002933, 'nationalityupdate', '2023-01-07 13:30:03.598047+00', true, '\xb884d4daabef9c6c90f052aac3b3790fe0b2fbc3bba4906668603a6871b5f484068927e457daeb1ae8bd12149d15ff2d', 13053297);
INSERT INTO public._sqlx_migrations VALUES (20210725221543, 'player claims', '2023-01-07 13:30:03.611805+00', true, '\xfc16737d3c511da863cc0e6d60ebe09d914b0032a7c7e199f9502986ce5d1767f3f0ad86cdc7cdacd7d818103ddcb21e', 1313531);
INSERT INTO public._sqlx_migrations VALUES (20210726174613, 'nation ranking', '2023-01-07 13:30:03.613816+00', true, '\x5c35046e56dbd7f913f29bb098eb0004be133273565aed1b0e5144837908f9f213df74e3236672a5e90c661645ca6fb9', 2258194);
INSERT INTO public._sqlx_migrations VALUES (20210825182933, 'new claim system', '2023-01-07 13:30:03.616775+00', true, '\xe0db241b57e88b76ba15a1ee62d4dc434569499e6acc2d1c10c5b0218ac7215da77273230d6f0095d347799bfe5ca5a1', 3219758);
INSERT INTO public._sqlx_migrations VALUES (20210903174349, 'subdivision ranking', '2023-01-07 13:30:03.620676+00', true, '\xe97e76554665cfbe2c6f532ec9536e3000767e8a4d4330ec7b725ea6075e3fb99da062ec8587aa1a625a0c88444766e2', 1231693);
INSERT INTO public._sqlx_migrations VALUES (20220323105850, 'member add email column', '2023-01-07 13:30:03.622549+00', true, '\x3381d9f9b7d7917aca6d4df31bb85826a4b010c86e0420080e18d3d61b419c3d259dfc17b24a011724940a99e9af5d25', 4568431);
INSERT INTO public._sqlx_migrations VALUES (20220324104659, 'lock submissions', '2023-01-07 13:30:03.627768+00', true, '\xeee564141dfdf3dd9d3a2e83a562b7f03d1b1bc2edb8140f5f877d397ac00fa2c26f80bf5ea620381992d43c3dc22836', 851796);
INSERT INTO public._sqlx_migrations VALUES (20220412171531, 'public notes', '2023-01-07 13:30:03.629297+00', true, '\x64253926a85b1c5df5d7ea050f47b3e83c301be424b10a9848b8abf3799c649cd9af4fbbc134bf2973565cfb04675b33', 924438);
INSERT INTO public._sqlx_migrations VALUES (20220601192100, 'extended list buff', '2023-01-07 13:30:03.630915+00', true, '\xdd863692d612086f818cb06ab1892ddf94e3f9da4e31c9480d48deb2a9750002d12e2f750dc19de7ab1f2fd30f8f5fdd', 987670);
INSERT INTO public._sqlx_migrations VALUES (20220805215800, 'fix youtube channel audit', '2023-01-07 13:30:03.632516+00', true, '\x322906c0fcc40ca5541ec518b2928bb3bdca7394ee4844403c642dba07a0676a828f4f260ac5dfbf14ba651ed6e4be1e', 766651);
INSERT INTO public._sqlx_migrations VALUES (20221009140916, 'thumbnails', '2023-01-07 13:30:03.633867+00', true, '\xb00dc8dd9aaced8e844b7105e241b3bb5a96d5cf39137782cc5fcf898ef99ba3a00751b11f05a2dd70561ce812874578', 1680974);

ALTER TABLE ONLY public._sqlx_migrations
    ADD CONSTRAINT _sqlx_migrations_pkey PRIMARY KEY (version);
